Add Local Endpoint
SwiftLeeds/swiftleeds-ios pull request #19
Opened 2022-08-08 19:28 UTC by SwiftyAlex

Adds the local endpoint to the app, and connects the local screen to it.

## Changes

Copies the approach as close as I could from the Schedule endpoint, so using nested models etc rather than separate, and using the endpoint name as the top level model name.

To avoid creating `Network` in every model, I've injected it via the Environment so we can have a shared network injected at the top level instead. 

The only visual change is adding an error overlay if the request fails, like this, and a tiny bit of padding so that the content no longer gets obscured by the tab bar.

|🌝|🌚|
| - | - | 
|![Simulator Screen Shot - iPhone 13 - 2022-08-08 at 20 22 36](https://user-images.githubusercontent.com/13989549/183498098-ef4eb9e2-80d6-431c-ab06-7b1d1d548eb2.png)|![Simulator Screen Shot - iPhone 13 - 2022-08-08 at 20 22 48](https://user-images.githubusercontent.com/13989549/183498116-166f6052-131a-4c23-ad88-3dffd5fcca71.png)|

2022-08-08 19:29 UTC, SwiftyAlex commented on Packages/NetworkKit/Sources/NetworkKit/MockNetwork.swift
> +    public func performRequest<E>(endpoint: E) async throws -> E.DataType where E : Endpoint {
I noticed the protocol I copied over was missing the async function from its definition so I added it, and then added the relevant code to MockNetwork

2022-08-08 19:30 UTC, SwiftyAlex commented on SwiftLeeds/Views/Local/BottomSheetView.swift
> +    let error: Error?
I couldn't see an existing approach for error handling so kept it really basic for now as to leave It open for whoever else wants to do it

2022-08-08 19:31 UTC, SwiftyAlex commented on SwiftLeeds/Views/Local/BottomSheetView.swift
> +                    .transition(.opacity)
I've added a transition to handle just in-case someone else animates higher up the hierarchy, but I haven't explicitly added an animation in this file

2022-08-08 19:31 UTC, SwiftyAlex commented on SwiftLeeds/Views/Local/BottomSheetView.swift
> +        static let tabBarPadding: CGFloat = UITabBar().frame.height
This makes me cringe a bit but I've never found a way around getting the exact number in SwiftUI 🤔

2022-08-10 16:33 UTC, pdamonkey requested changes

2022-08-10 16:33 UTC, pdamonkey commented on SwiftLeeds/Network/ScheduleEndpoint.swift
> -// MARK: - Environment
This should be put back to `Endpoints.swift`, named on purpose to contain all endpoints of the App (as there aren't many and saves lots of small files)

2022-08-12 15:41 UTC, pdamonkey approved these changes

2022-08-12 16:36 UTC, merged