Design tweaks for initial screen
SwiftLeeds/swiftleeds-ios pull request #4
Opened 2022-06-27 11:13 UTC by SwiftyAlex

A few small changes from the discussion on the PR for the initial screen:

- Update type to help separate things better
- Update dynamic type on the announcement cells so that they flex based on size a little differently 

| Dynamic Type | Normal type | 
| - | - | 
|![Simulator Screen Shot - iPhone 13 - 2022-06-27 at 12 09 10](https://user-images.githubusercontent.com/13989549/175928679-678d7324-16c6-4b6c-a9bf-ed342bea2493.png)|![Simulator Screen Shot - iPhone 13 - 2022-06-27 at 12 08 45](https://user-images.githubusercontent.com/13989549/175928703-f29c16a2-ce3e-4f1b-8748-bf7cb218cd1b.png)|

2022-07-02 20:27 UTC, SwiftyAlex commented on SwiftLeeds/Resources/Colors.xcassets/Gradients/WeatherGradientEnd.colorset/Contents.json
> +        "color-space" : "display-p3",
I'll flick this back, I opened them and looks like ive changed this one somehow 🤔

2022-07-03 09:00 UTC, pdamonkey requested changes

2022-07-03 10:58 UTC, SwiftyAlex commented on SwiftLeeds/Resources/Colors.xcassets/Gradients/WeatherGradientStart.colorset/Contents.json
> +        "color-space" : "display-p3",
They're now all SRGB, and I've made them consistently use hex as input rather than them being dotted around

2022-07-03 11:51 UTC, pdamonkey approved these changes

2022-07-03 13:20 UTC, merged